"use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const Amaz = effect.Amaz;
    let Core = undefined;
    let globalDefine = undefined;
    try {
      Core = require('AmazingProJS/APJSCore');
    } catch (e) {}
    if (Core) {
      console.log('require APJSCore success!');
      globalDefine = Core;
    } else {
      globalDefine = require('AmazingProJS/GlobalDefine');
    }
    function _lazyRequire(_moduleName, _modulePath) {
        if (typeof _modulePath != "undefined") {
            if(Core && Core[_moduleName]) {
                exports[_moduleName] = Core[_moduleName];
                Core.s_nameToModule.set(_modulePath, Core);
                return;
            }
            else {
                globalDefine.globalModuleNameToFileMap.set(_moduleName, _modulePath);
            }
        }
        Object.defineProperty(exports, _moduleName, {
            get() {
              const internalName = '_' + _moduleName;
              if (exports[internalName]) {
                  return exports[internalName];
              }
              else {
                //@ts-ignore
                if (typeof _modulePath != "undefined") {
                    let res = globalDefine.APJS_Require(_modulePath);
                    exports[internalName] = res[_moduleName];
                }
                else {
                    exports[internalName] = effect.Amaz[_moduleName];
                }
                return exports[internalName];
              }
            },
            enumerable: true,
            configurable: true
        });
    }

_lazyRequire('Guid', 'Guid');
_lazyRequire('AObject', 'AObject');
_lazyRequire('Event', 'Event');
_lazyRequire('LayerSet', 'LayerSet');
_lazyRequire('Vector2f', 'Vector2');
_lazyRequire('Vector3f', 'Vector3');
_lazyRequire('Vector4f', 'Vector4');
_lazyRequire('Quaternionf', 'Quaternionf');
_lazyRequire('Matrix3x3f', 'Matrix3x3');
_lazyRequire('Matrix4x4f', 'Matrix4x4');
_lazyRequire('Color', 'Color');
_lazyRequire('AABB', 'AABB');
_lazyRequire('Ray', 'Ray');
_lazyRequire('Sphere', 'Sphere');
_lazyRequire('Rect', 'Rect');
_lazyRequire('MathNativeObjectPool', 'MathNativeObjectPool');
_lazyRequire('Vector', 'Vector');
_lazyRequire('Map', 'Map');
_lazyRequire('DynamicBitset', 'DynamicBitset');
_lazyRequire('Vec2Vector', 'Vec2Vector');
_lazyRequire('Vec4Vector', 'Vec4Vector');
_lazyRequire('Vec3Vector', 'Vec3Vector');
_lazyRequire('Int8Vector', 'Int8Vector');
_lazyRequire('Int16Vector', 'Int16Vector');
_lazyRequire('Int32Vector', 'Int32Vector');
_lazyRequire('Int64Vector', 'Int64Vector');
_lazyRequire('UInt8Vector', 'UInt8Vector');
_lazyRequire('UInt16Vector', 'UInt16Vector');
_lazyRequire('UInt32Vector', 'UInt32Vector');
_lazyRequire('FloatVector', 'FloatVector');
_lazyRequire('DoubleVector', 'DoubleVector');
_lazyRequire('QuatVector', 'QuatVector');
_lazyRequire('StringVector', 'StringVector');
_lazyRequire('Mat3Vector', 'Mat3Vector');
_lazyRequire('Mat4Vector', 'Mat4Vector');
_lazyRequire('AMGComputeEntity', 'ComputeEntity');
_lazyRequire('Component', 'Component');
_lazyRequire('SceneObject', 'Scene');
_lazyRequire('Prefab', 'Prefab');
_lazyRequire('Scene', 'Scene');
_lazyRequire('System', 'System');
_lazyRequire('Transform', 'Transform');
_lazyRequire('CommandBuffer', 'CommandBuffer');
_lazyRequire('DynamicComponent', 'DynamicComponent');
_lazyRequire('BasicScriptComponent', 'BasicScriptComponent');
_lazyRequire('Provider', 'TextureProvider');
_lazyRequire('MeshProvider', 'MeshProvider');
_lazyRequire('Face3DMeshProvider', 'Face3DMeshProvider');
_lazyRequire('Buffer', 'Buffer');
_lazyRequire('Material', 'Material');
_lazyRequire('MaterialPropertyBlock', 'Material');
_lazyRequire('Mesh', 'Mesh');
_lazyRequire('AnimatedMesh', 'AnimatedMesh');
_lazyRequire('Skin', 'Skin');
_lazyRequire('Morpher', 'Morpher');
_lazyRequire('PropertySheet', 'PropertySheet');
_lazyRequire('RenderState', 'RenderState');
_lazyRequire('VertexAttributeDesc', 'MeshCreateDesc');
_lazyRequire('MeshCreateDesc', 'MeshCreateDesc');
_lazyRequire('SubMeshCreateDesc', 'MeshCreateDesc');
_lazyRequire('FaceMeshCreateDesc', 'MeshCreateDesc');
_lazyRequire('MeshUtils', 'MeshUtils');
_lazyRequire('ImageAsset', 'ImageAsset');
_lazyRequire('RenderTextureCreateDesc', 'RenderTextureCreateDesc');
_lazyRequire('RenderTextureProvider', 'ScreenTextureProvider');
_lazyRequire('SceneOutputRTProvider', 'SceneOutputRTProvider');
_lazyRequire('ScreenTextureCreateDesc', 'ScreenTextureCreateDesc');
_lazyRequire('ScreenTextureProvider', 'ScreenTextureProvider');
_lazyRequire('Texture', 'Texture');
_lazyRequire('Texture2DProvider', 'Texture2DProvider');
_lazyRequire('Texture3DProvider', 'Texture3DProvider');
_lazyRequire('TextureCreateDesc', 'TextureCreateDesc');
_lazyRequire('TextureCubeProvider', 'TextureCubeProvider');
_lazyRequire('TextureProvider', 'TextureProvider');
_lazyRequire('PlaceHolderTextureProvider', 'PlaceHolderTextureProvider');
_lazyRequire('TextureDelegateProvider', 'TextureDelegateProvider');
_lazyRequire('DrawTextureProvider', 'DrawTextureProvider');
_lazyRequire('Texture2DCreateDesc', 'Texture2DCreateDesc');
_lazyRequire('Texture3DCreateDesc', 'Texture3DCreateDesc');
_lazyRequire('TextureCubeCreateDesc', 'TextureCubeCreateDesc');
_lazyRequire('DrawTextureCreateDesc', 'DrawTextureCreateDesc');
_lazyRequire('TextureUtils', 'TextureUtils');
_lazyRequire('AssetManager', 'AssetManager');
_lazyRequire('CustomAssetsMap', 'AssetManager');
_lazyRequire('AngleBinaryProgram', 'AngleBinaryProgram');
_lazyRequire('AMGBeautyMeshType');
_lazyRequire('ARUnit');
_lazyRequire('AffectorCollisionType');
_lazyRequire('AffectorForceApplication');
_lazyRequire('AffectorIntersectionType');
_lazyRequire('AffectorScaleType');
_lazyRequire('AffectorTextureAnimationType');
_lazyRequire('AnimSeqEventType');
_lazyRequire('AnimSequenceEventType');
_lazyRequire('AnimTimeType');
_lazyRequire('AnimatorCullingMode');
_lazyRequire('AnimationEventType', 'Enum');
_lazyRequire('AnimationBindType', 'Enum');
_lazyRequire('AreaShape');
_lazyRequire('AsyncLoadState');
_lazyRequire('BEFEventType');
_lazyRequire('BEF_RECODE_VEDIO_EVENT_CODE');
_lazyRequire('BEFTimerType');
_lazyRequire('BehaviorWhenTrackerDisappear');
_lazyRequire('BlendFactor', 'Enum');
_lazyRequire('BrushDrawingType');
_lazyRequire('BrushLocalFrameType');
_lazyRequire('BrushSegment');
_lazyRequire('BuiltInTextureType');
_lazyRequire('CalibrationType');
_lazyRequire('CameraClearType', 'Enum');
_lazyRequire('CameraSortMethod');
_lazyRequire('CameraPosition');
_lazyRequire('CameraRTBackupMode');
_lazyRequire('CameraType', 'Enum');
_lazyRequire('CameraFovType', 'Enum');
_lazyRequire('CanvasRenderMode');
_lazyRequire('CaptureType');
_lazyRequire('CaptureVersion');
_lazyRequire('CollideDirection');
_lazyRequire('Collider3DFlag');
_lazyRequire('CollisionDetectionType');
_lazyRequire('ColorOperation');
_lazyRequire('StencilFunction', 'Enum');
_lazyRequire('DepthFunction', 'Enum');
_lazyRequire('ComponentOverrideType');
_lazyRequire('ConeEmitterEmitFrom');
_lazyRequire('ContextType');
_lazyRequire('CubeMapTexType');
_lazyRequire('CullMode', 'Enum');
_lazyRequire('DataType');
_lazyRequire('DeviceOrientation');
_lazyRequire('MakeupType', 'Enum');
_lazyRequire('EffectNodeTag');
_lazyRequire('EntityOverrideType');
_lazyRequire('EntityRotateType');
_lazyRequire('EventPriority');
_lazyRequire('EventSource');
_lazyRequire('Face3DMeshType', 'Enum');
_lazyRequire('FaceLiquifyVersionType');
_lazyRequire('FaceMakeUpType');
_lazyRequire('FaceReshapeLiquefyPetMeshType');
_lazyRequire('FaceReshapeLiquefyType');
_lazyRequire('TextBackgroundRenderType');
_lazyRequire('FaceStretchType');
_lazyRequire('FaceWarpXRendererVersion');
_lazyRequire('NsItemType');
_lazyRequire('FeatureType');
_lazyRequire('FilterMipmapMode', 'Enum');
_lazyRequire('FilterMode', 'Enum');
_lazyRequire('FontDecorationType');
_lazyRequire('FontStyle');
_lazyRequire('FrontFace');
_lazyRequire('GestureEvent');
_lazyRequire('GestureRecognizerState');
_lazyRequire('GestureType');
_lazyRequire('GradientStyle');
_lazyRequire('GradientType');
_lazyRequire('HapticsModule', 'HapticsModule');
_lazyRequire('IFAnchorAlignmentTrackOption');
_lazyRequire('IFAnchorAlignmentType');
_lazyRequire('IFBlendMode');
_lazyRequire('IFFilledType');
_lazyRequire('IFGenderType');
_lazyRequire('IFLayer2dRenderOrderMode');
_lazyRequire('IFMaskType');
_lazyRequire('IFObjectType');
_lazyRequire('IFPseudo3DType');
_lazyRequire('IFResolutionType');
_lazyRequire('IFRotationType');
_lazyRequire('IFSprite2dSizeMode');
_lazyRequire('IFSprite2dType');
_lazyRequire('IFTweenControlMode');
_lazyRequire('IFTweenCurveType');
_lazyRequire('IFTweenStyle');
_lazyRequire('IFUIConstraintsExecute');
_lazyRequire('IFUIConstraintsMode');
_lazyRequire('IFUIGridHorizontalDirection');
_lazyRequire('IFUIGridResizeMode');
_lazyRequire('IFUIGridSortingType');
_lazyRequire('IFUIGridStartAxis');
_lazyRequire('IFUIGridType');
_lazyRequire('IFUIGridVerticalDirection');
_lazyRequire('IFUILabelAlignment');
_lazyRequire('IFUILabelFitType');
_lazyRequire('IFUILabelFontType');
_lazyRequire('IFUIMoveDirection');
_lazyRequire('IFUISafeAreaType');
_lazyRequire('IFUIScrollDirection');
_lazyRequire('IFUISliderMode');
_lazyRequire('ImageStretchMode');
_lazyRequire('AeBundleImageStretchMode');
_lazyRequire('StretchMode', 'Enum');
_lazyRequire('Input', 'Input');
_lazyRequire('InputListener');
_lazyRequire('AccelerationSensorAgent', 'Input');
_lazyRequire('GravitySensorAgent', 'Input');
_lazyRequire('GyroSensorAgent', 'Input');
_lazyRequire('RotationSensorAgent', 'Input');
_lazyRequire('RateSensorAgent', 'Input');
_lazyRequire('InternalFormat');
_lazyRequire('InterpolationType', 'Enum');
_lazyRequire('JsDownloadStatus');
_lazyRequire('JsTaskStatus');
_lazyRequire('AnimationLayerType', 'Enum');
_lazyRequire('LightMode');
_lazyRequire('LightProbeBlendMode');
_lazyRequire('LightRenderMode');
_lazyRequire('LineBreakType', 'Enum');
_lazyRequire('GradientQuality', 'Enum');
_lazyRequire('LayoutMode');
_lazyRequire('LookAtDirection', 'LookAt');
_lazyRequire('LookAtMode', 'LookAt');
_lazyRequire('LookAtWorldUp', 'LookAt');
_lazyRequire('MSAAMode');
_lazyRequire('MeshCenter');
_lazyRequire('MeshCurve');
_lazyRequire('MeshNormal');
_lazyRequire('ExtrudeDir');
_lazyRequire('MeshTopology', 'Enum');
_lazyRequire('MeshUVType');
_lazyRequire('Mobility');
_lazyRequire('ParticleMeshRendererType');
_lazyRequire('ParticleOritationDisplay');
_lazyRequire('ParticleOritationMode');
_lazyRequire('ParticleQuatRendererAlignType');
_lazyRequire('ParticleQuatRendererOrientationType');
_lazyRequire('ParticleRenderSortingMode');
_lazyRequire('ParticleRingBufferMode');
_lazyRequire('ParticleSimulationSpace');
_lazyRequire('ParticleUpdateMode');
_lazyRequire('PassClearMoment');
_lazyRequire('PassType');
_lazyRequire('PinOrientation');
_lazyRequire('PixelFormat');
_lazyRequire('PlayMode');
_lazyRequire('PolygonMode');
_lazyRequire('PortValueType');
_lazyRequire('PrefabStatus');
_lazyRequire('Primitive');
_lazyRequire('RaycasterType');
_lazyRequire('RenderPipelineType');
_lazyRequire('RenderTextureAttachment');
_lazyRequire('RendererType');
_lazyRequire('RigidBodyType');
_lazyRequire('RotateType');
_lazyRequire('SensorDataSpace');
_lazyRequire('SensorType');
_lazyRequire('TimeRangeSourceMode');
_lazyRequire('SensorFilterType');
_lazyRequire('SeqAssetType');
_lazyRequire('ShaderType', 'Enum');
_lazyRequire('StateTransitionType');
_lazyRequire('StencilOperation', 'Enum');
_lazyRequire('SubEmitterType');
_lazyRequire('TexSeqAssetType');
_lazyRequire('TextAlign');
_lazyRequire('TextLocale');
_lazyRequire('TextTypeSettingParam', 'TextTypeSettingParam');
_lazyRequire('TextCanvas', 'TextCanvas');
_lazyRequire('Texture2DAssetFormat');
_lazyRequire('TouchPhase', 'TouchData');
_lazyRequire('AnimationTrackDataType', 'Enum');
_lazyRequire('TrackingMode');
_lazyRequire('TrackingType');
_lazyRequire('TrailTextureMode');
_lazyRequire('TypeSettingKind');
_lazyRequire('TypesettingAlign');
_lazyRequire('TypesettingAlignVertical');
_lazyRequire('TypesettingDirect');
_lazyRequire('TypesettingKind');
_lazyRequire('UniformBinding');
_lazyRequire('VFXBlendMode');
_lazyRequire('VFXBufferDataType');
_lazyRequire('VFXEventType');
_lazyRequire('ValueCurveInterpolationType');
_lazyRequire('ValueCurvedInterpolationType');
_lazyRequire('ValueOscillationType');
_lazyRequire('VertexAttribType');
_lazyRequire('VertexAttributeType', 'Enum');
_lazyRequire('WrapMode', 'Enum');
_lazyRequire('JSScriptComponent', 'JSScriptComponent');
_lazyRequire('Camera', 'Camera');
_lazyRequire('IFLayer2d', 'IFLayer2d');
_lazyRequire('Model', 'Model');
_lazyRequire('MaskData', 'MaskRenderer');
_lazyRequire('MaskRenderer', 'MaskRenderer');
_lazyRequire('MeshRenderer', 'MeshRenderer');
_lazyRequire('SkinMeshRenderer', 'SkinMeshRenderer');
_lazyRequire('VisualEffectAsset', 'VisualEffectAsset');
_lazyRequire('XShader', 'XShader');
_lazyRequire('VideoAsset', 'VideoAsset');
_lazyRequire('Mp4LoadConfig', 'VideoAsset');
_lazyRequire('ArtTextAsset', 'ArtTextAsset');
_lazyRequire('Pass', 'Pass');
_lazyRequire('ScriptComponent', 'ScriptComponent');
_lazyRequire('BlendState', 'RenderState');
_lazyRequire('ColorBlendAttachmentState', 'RenderStateLegacy');
_lazyRequire('StencilState', 'RenderState');
_lazyRequire('RasterizationState', 'RenderStateLegacy');
_lazyRequire('ViewportState', 'RenderStateLegacy');
_lazyRequire('Shader', 'Shader');
_lazyRequire('SubMesh', 'Mesh');
_lazyRequire('VertexAttribDesc', 'VertexAttribDesc');
_lazyRequire('Renderer', 'Renderer');
_lazyRequire('Plane', 'Plane');
_lazyRequire('Profiler', 'Profiler');
_lazyRequire('IFTransform2d', 'IFTransform2d');
_lazyRequire('AmazingUtil', 'AmazingUtil');
_lazyRequire('DeviceInfo', 'DeviceInfo');
_lazyRequire('OS', 'DeviceInfo');
_lazyRequire('Hand3DUtil', 'Head3DUtil');
_lazyRequire('KeywordProgramProfile', 'KeywordProgramProfile');
_lazyRequire('AnimSeq', 'AnimSeq');
_lazyRequire('AmazingManager', 'AmazingManager');
_lazyRequire('WatchValueManager', 'WatchValueManager');
_lazyRequire('ResetPropertyManager', 'ResetPropertyManager');
_lazyRequire('SceneManager', 'SceneManager');
_lazyRequire('ShaderSnippet', 'ShaderSnippet');
_lazyRequire('VFXContextBlock', 'VFXContextBlock');
_lazyRequire('VisualEffect', 'VisualEffect');
_lazyRequire('VFXBuffer', 'VFXBuffer');
_lazyRequire('VFXBufferData', 'VFXBufferData');
_lazyRequire('Animation', 'Animation');
_lazyRequire('Physics3D', 'Physics3D');
_lazyRequire('Physics2D', 'Physics2D');
_lazyRequire('ContactInfo2D', 'Physics2D');
_lazyRequire('ScreenTransform', 'ScreenTransform');
_lazyRequire('Image', 'Image');
_lazyRequire('AnimSeqComponent', 'AnimSeqComponent');
_lazyRequire('Animator', 'Animator');
_lazyRequire('EffectNode', 'EffectNode');
_lazyRequire('BehaviorComponent', 'BehaviorComponent');
_lazyRequire('IFPetAnchorAlignment', 'IFPetAnchorAlignment');
_lazyRequire('AudioAsset', 'AudioAsset');
_lazyRequire('ColorMask', 'Enum');
_lazyRequire('ProxyVector3f', 'ProxyVector3f');
_lazyRequire('AMGChar', 'AMGChar');
_lazyRequire('Joint', 'Joint');
_lazyRequire('BlendOperation', 'Enum');
_lazyRequire('Joint3D', 'Joint3D');
_lazyRequire('FixedJoint', 'FixedJoint');
_lazyRequire('PointJoint', 'PointJoint');
_lazyRequire('HingeJoint', 'HingeJoint');
_lazyRequire('SpringJoint', 'SpringJoint');
_lazyRequire('DynamicChain', 'DynamicChain');
_lazyRequire('EffectNodeEvent');
_lazyRequire('StencilOpState', 'RenderStateLegacy');
_lazyRequire('PointCache', 'PointCache');
_lazyRequire('AttributeMap', 'AttributeMap');
_lazyRequire('ImageProvider', 'ImageProvider');
_lazyRequire('CubeCrossImageProvider', 'ImageProvider');
_lazyRequire('CubeImageProvider', 'ImageProvider');
_lazyRequire('ImageAtlas', 'ImageAtlas');
_lazyRequire('MorpherComponent', 'MorpherComponent');
_lazyRequire('MorpherChannel', 'Morpher');
_lazyRequire('Light', 'Light');
_lazyRequire('ModelNode', 'ModelNode');
_lazyRequire('AnimationTrack', 'AnimationTrack');
_lazyRequire('MorpherTarget', 'Morpher');
_lazyRequire('FaceCapture', 'FaceCapture');
_lazyRequire('TextureSequence', 'TextureSequence');
_lazyRequire('IFSprite2d', 'IFSprite2d');
_lazyRequire('IFWidget', 'IFWidget');
_lazyRequire('IFAnchorAlignment', 'IFAnchorAligment');
_lazyRequire('ImageFrame', 'ImageFrame');
_lazyRequire('PointLight', 'PointLight');
_lazyRequire('DirectionalLight', 'DirectionalLight');
_lazyRequire('SpotLight', 'SpotLight');
_lazyRequire('IFCanvas2d', 'IFCanvas2d');
_lazyRequire('IFFaceAnchorAlignment', 'IFFaceAnchorAlignment');
_lazyRequire('FaceMakeup', 'FaceMakeup');
_lazyRequire('FaceMakeupIris', 'FaceMakeupIris');
_lazyRequire('AnimSequenceEventInfo', 'AnimSequenceEventInfo');
_lazyRequire('IFHandAnchorAlignment', 'IFHandAnchorAlignment');
_lazyRequire('IFSkeletonAnchorAlignment', 'IFSkeletonAnchorAlignment');
_lazyRequire('FaceStretchComponent', 'FaceStretchComponent');
_lazyRequire('LookAt', 'LookAt');
_lazyRequire('PinToMesh', 'PinToMesh');
_lazyRequire('AlgorithmAsset', 'AlgorithmAsset');
_lazyRequire('Sprite2DRenderer', 'Sprite2DRenderer');
_lazyRequire('CameraEvent');
_lazyRequire('AppEventType');
_lazyRequire('BuiltinObject', 'BuiltinObject');
_lazyRequire('EventType', 'EventType');
_lazyRequire('RenderCacheEventType');
_lazyRequire('RenderCacheStatus');
_lazyRequire('getSerializeProperties', 'GlobalDefine');
_lazyRequire('Preset', 'Preset');
_lazyRequire('EnvironmentLight', 'EnvironmentLight');
_lazyRequire('PhysicsMaterial', 'PhysicsMaterial');
_lazyRequire('TextureMeta', 'Meta');
_lazyRequire('FaceInsetRenderer', 'FaceInsetRenderer');
_lazyRequire('FaceInsetMeshGenerator', 'FaceInsetMeshGenerator');
_lazyRequire('FaceWarpXRenderer', 'FaceWarpXRenderer');
_lazyRequire('FaceWarpXModelInfo', 'FaceWarpXModelInfo');
_lazyRequire('FaceWarpXWarpInfo', 'FaceWarpXWarpInfo');
_lazyRequire('FaceWarpXToolUtils', 'FaceWarpXToolUtils');
_lazyRequire('NsItem', 'NsItem');
_lazyRequire('NsEditorUtils', 'NsEditorUtils');
_lazyRequire('TextBendType', 'TextTypeSettingParam');
_lazyRequire('TextOnPathBase', 'TextTypeSettingParam');
_lazyRequire('TextOnArc', 'TextTypeSettingParam');
_lazyRequire('BaseText', 'BaseText');
_lazyRequire('Text', 'Text');
_lazyRequire('TextAnimationType', 'Enum');
_lazyRequire('Text3D', 'Text3D');
_lazyRequire('Text3DVerticalAlignment', 'Text3D');
_lazyRequire('Text3DHorizontalAlignment', 'Text3D');
_lazyRequire('TextBackground', 'TextBackground');
_lazyRequire('JSScript', 'JSScript');
_lazyRequire('JsonAsset', 'JsonAsset');
_lazyRequire('RawText', 'RawText');
_lazyRequire('getEngineVersion', 'GlobalDefine');
_lazyRequire('isAPJSType', 'GlobalDefine');
_lazyRequire('transferToAPJSObj', 'GlobalDefine');
_lazyRequire('encodeProperty', 'Reflection');
_lazyRequire('decodePropertyToList', 'Reflection');
_lazyRequire('isEncodeProperty', 'Reflection');
_lazyRequire('AMGClothInfo', 'AMGClothInfo');
_lazyRequire('AMGSoftBodyInfo', 'AMGSoftBodyInfo');
_lazyRequire('AMGTetMeshInfo', 'AMGTetMeshInfo');
_lazyRequire('AMGVolumetricMeshUtils', 'AMGVolumetricMeshUtils');
_lazyRequire('AMGPointSampler', 'AMGPointSampler');
_lazyRequire('AMGCollisionFinder', 'AMGCollisionFinder');
_lazyRequire('AMGContactInfo', 'AMGContactInfo');
_lazyRequire('AMGModifiedProperty', 'AMGModifiedProperty');
_lazyRequire('AMGModifiedPropertyHandler', 'AMGModifiedPropertyHandler');
_lazyRequire('AMGPbdSimulator', 'AMGPbdSimulator');
_lazyRequire('AMGSimulator2D', 'AMGSimulator2D');
_lazyRequire('AMGRayHitInfo', 'AMGRayHitInfo');
_lazyRequire('SceneUtils', 'SceneUtils');
_lazyRequire('SignalUtils', 'SignalUtils');
_lazyRequire('RigidBody', 'RigidBody');
_lazyRequire('RigidBody2D', 'RigidBody2D');
_lazyRequire('Collider', 'Collider');
_lazyRequire('BoxCollider', 'BoxCollider');
_lazyRequire('SphereCollider', 'SphereCollider');
_lazyRequire('CapsuleCollider', 'CapsuleCollider');
_lazyRequire('MeshCollider', 'MeshCollider');
_lazyRequire('GSplatCollider', 'GSplatCollider');
_lazyRequire('Collider2D', 'Collider2D');
_lazyRequire('BoxCollider2D', 'BoxCollider2D');
_lazyRequire('CircleCollider2D', 'CircleCollider2D');
_lazyRequire('EdgeCollider2D', 'EdgeCollider2D');
_lazyRequire('PolygonCollider2D', 'PolygonCollider2D');
_lazyRequire('AnimationClip', 'AnimationClip');
_lazyRequire('getAPPropNameByRttiPropName', 'Reflection');
_lazyRequire('getRttiPropNameByAPPropName', 'Reflection');
_lazyRequire('getRttiPropNameByAPPropFullName', 'Reflection');
_lazyRequire('objHasProperty', 'Reflection');
_lazyRequire('checkAndClearHandleCache', 'GlobalDefine');
_lazyRequire('EngineState', 'GlobalDefine');
_lazyRequire('getNativeFromObj', 'GlobalDefine');
_lazyRequire('getNativeExternal', 'GlobalDefine');
_lazyRequire('getConstructorByName', 'GlobalDefine');
_lazyRequire('LetterStyle', 'LetterStyle');
_lazyRequire('LetterStyleLayer', 'LetterStyleLayer');
_lazyRequire('LetterStyleLayerType');
_lazyRequire('LetterStyleLayerRenderType');
_lazyRequire('LetterStyleLayerGradientMode');
_lazyRequire('LetterStyleLayerTextureBlend');
_lazyRequire('Letter', 'Letter');
_lazyRequire('TouchData', 'TouchData');
_lazyRequire('AppInfo', 'AppInfo');
_lazyRequire('AudioNodePin', 'AudioGraph');
_lazyRequire('AudioNodePout', 'AudioGraph');
_lazyRequire('AudioGraphNode', 'AudioGraph');
_lazyRequire('AudioSourceNode', 'AudioGraph');
_lazyRequire('AudioMicSourceNode', 'AudioGraph');
_lazyRequire('AudioMusicSourceNode', 'AudioGraph');
_lazyRequire('AudioGainNode', 'AudioGraph');
_lazyRequire('AudioEffectNode', 'AudioGraph');
_lazyRequire('AudioExtractorResult', 'AudioGraph');
_lazyRequire('AudioExtractorNode', 'AudioGraph');
_lazyRequire('AudioGraph', 'AudioGraph');
_lazyRequire('AudioFeature', 'AudioFeature');
_lazyRequire('AudioGraphAssembler', 'AudioGraphAssembler');
_lazyRequire('AudioClipPlayer', 'AudioGraphAssembler');
_lazyRequire('KeywordNodeManager', 'KeywordNodeManager');
_lazyRequire('AnimationLayer', 'AnimationLayer');
_lazyRequire('AnimationState', 'AnimationState');
_lazyRequire('GifAsset', 'GifAsset');
_lazyRequire('GifLoadConfig', 'GifAsset');
_lazyRequire('TableComponent', 'TableComponent');
_lazyRequire('CameraFitMode');
_lazyRequire('AnalyticsManager', 'AnalyticsManager');
_lazyRequire('AnalyticsData', 'AnalyticsManager');
_lazyRequire('userPrivateAPI', 'UserDecorator');
_lazyRequire('userPublicAPI', 'UserDecorator');
_lazyRequire('hideAPIPrototype', 'UserDecorator');
_lazyRequire('EnterInternalScope', 'UserDecorator');
_lazyRequire('QuitInternalScope', 'UserDecorator');
_lazyRequire('enableUserScript', 'UserDecorator');
_lazyRequire('WidgetBase', 'UIAnnotationDecorator');
_lazyRequire('ColorWidget', 'UIAnnotationDecorator');
_lazyRequire('RangeWidget', 'UIAnnotationDecorator');
_lazyRequire('DropDownWidget', 'UIAnnotationDecorator');
_lazyRequire('TextAreaWidget', 'UIAnnotationDecorator');
_lazyRequire('EventManager', 'EventManager');
_lazyRequire('NetworkManager', 'NetworkManager');
_lazyRequire('RequestTask', 'RequestTask');
_lazyRequire('SceneEventType', 'EventManager');
_lazyRequire('Joint2D', 'Joint2D');
_lazyRequire('SpringJoint2D', 'SpringJoint2D');
_lazyRequire('DistanceJoint2D', 'DistanceJoint2D');
_lazyRequire('HingeJoint2D', 'HingeJoint2D');
_lazyRequire('FixedJoint2D', 'FixedJoint2D');
_lazyRequire('CollisionEvent', 'CollisionEvent');
_lazyRequire('CollisionEvent2D', 'CollisionEvent2D');
_lazyRequire('CollisionInfo', 'CollisionEvent');
_lazyRequire('CollisionInfo2D', 'CollisionEvent2D');
_lazyRequire('RaycastHit3D', 'CollisionEvent');
_lazyRequire('RaycastHit2D', 'CollisionEvent2D');
_lazyRequire('User_Require', 'UserRequire');
_lazyRequire('AnimatedTextureProvider', 'AnimatedTextureProvider');
_lazyRequire('AnimatedTexturePlayMode', 'AnimatedTextureProvider');
_lazyRequire('AnimatedTextureEvent', 'AnimatedTextureProvider');
_lazyRequire('AnimatedTextureCreateDesc', 'AnimatedTextureProvider');
_lazyRequire('GifTextureProvider', 'GifTextureProvider');
_lazyRequire('GifEvent', 'GifTextureProvider');
_lazyRequire('Mp4TextureProvider', 'Mp4TextureProvider');
_lazyRequire('Mp4Event', 'Mp4TextureProvider');
_lazyRequire('setDynamicAssetRuntimeManager', 'DynamicAssetRuntimeManager');
_lazyRequire('getDynamicAssetRuntimeManager', 'DynamicAssetRuntimeManager');
_lazyRequire('DynamicAssetRuntimeManager', 'DynamicAssetRuntimeManager');
_lazyRequire('isDynamicAsset', 'DynamicAssetRuntimeManager');
_lazyRequire('UserIndex', 'UserIndex');
_lazyRequire('isSerializeProperty', 'serialize');
_lazyRequire('dualInstanceProperty', 'DualInstance');
_lazyRequire('dualInstanceMethod', 'DualInstance');
_lazyRequire('isDualInstanceScriptProperty', 'DualInstance');
_lazyRequire('isDualInstanceScriptMethod', 'DualInstance');
_lazyRequire('GSplatRenderMode');
_lazyRequire('ScreenTextureSizeMode', 'ScreenTextureProvider');
_lazyRequire('GSplatRenderer', 'GSplatRenderer');
_lazyRequire('GSplat', 'GSplat');
_lazyRequire('registerClass', 'GlobalDefine');
_lazyRequire('decodePropertyToAccessor', 'GlobalDefine');
_lazyRequire('serialize', 'serialize');
_lazyRequire('clearObjectCache', 'GlobalDefine');
_lazyRequire('UserScriptComponentUtils', 'UserScriptComponentUtils');
_lazyRequire('ScriptCustomExternalObject', 'ScriptCustomExternalObject');
_lazyRequire('ScriptCustomObject', 'ScriptCustomObject');
_lazyRequire('isJSArraySerializedProperty', 'serialize');
_lazyRequire('isJSArrayDualInstanceProperty', 'DualInstance');
_lazyRequire('registerJSScriptDualInstanceMethod', 'DualInstance');
_lazyRequire('isJSScriptDualInstanceMethod', 'DualInstance');
_lazyRequire('addSceneObjectProperty', 'serialize');
_lazyRequire('clearSerializedDefaultValue', 'serialize');
_lazyRequire('clearSerializedCacheOfApjsObject', 'serialize');
_lazyRequire('getMemoryProfileAmazingProObjSet', 'GlobalDefine');
_lazyRequire('enableMemoryProfile', 'GlobalDefine');
_lazyRequire('executeAlways', 'GlobalDefine');
_lazyRequire('SharedMemoryReader', 'SharedMemoryReader');
_lazyRequire('RenderUtils', 'RenderUtils');
_lazyRequire('StretchModeUtils', 'StretchModeUtils');
_lazyRequire('PBDSystem', 'PBDSystem');
_lazyRequire('PhysicsSystem2D', 'PhysicsSystem2D');
_lazyRequire('systemScript', 'GlobalDefine');
_lazyRequire('systemList', 'GlobalDefine');
_lazyRequire('getSystemScriptCtorByName', 'GlobalDefine');
_lazyRequire('getDependentSystems', 'GlobalDefine');
_lazyRequire('convertJSArrayToVector2Array', 'CollectionUtils');
_lazyRequire('convertJSArrayToVector3Array', 'CollectionUtils');
_lazyRequire('convertJSArrayToVector4Array', 'CollectionUtils');
_lazyRequire('convertJSArrayToQuaternionArray', 'CollectionUtils');
_lazyRequire('convertJSArrayToNativeVector', 'RTTICollectionUtils');
_lazyRequire('convertNativeVectorToJSArray', 'RTTICollectionUtils');
_lazyRequire('convertNumberVectorToJSArray', 'RTTICollectionUtils');
_lazyRequire('convertNativeMapToJSMap', 'RTTICollectionUtils');
_lazyRequire('convertNativeInt8VectorToJSInt8Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeInt16VectorToJSInt16Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeInt32VectorToJSInt32Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeUInt8VectorToJSUint8Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeUInt16VectorToJSUint16Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeUInt32VectorToJSUint32Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeFloatVectorToJSFloat32Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeDoubleVectorToJSFloat64Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeVec2VectorToJSFloat32Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeVec3VectorToJSFloat32Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeVec4VectorToJSFloat32Array', 'RTTICollectionUtils');
_lazyRequire('convertNativeQuatVectorToJSFloat32Array', 'RTTICollectionUtils');
_lazyRequire('convertJSInt8ArrayToNativeInt8Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSInt16ArrayToNativeInt16Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSInt32ArrayToNativeInt32Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSUint8ArrayToNativeUInt8Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSUint16ArrayToNativeUInt16Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSUint32ArrayToNativeUInt32Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSFloat32ArrayToNativeFloatVector', 'RTTICollectionUtils');
_lazyRequire('convertJSFloat64ArrayToNativeDoubleVector', 'RTTICollectionUtils');
_lazyRequire('convertJSFloat32ArrayToNativeVec2Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSFloat32ArrayToNativeVec3Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSFloat32ArrayToNativeVec4Vector', 'RTTICollectionUtils');
_lazyRequire('convertJSFloat32ArrayToNativeQuatVector', 'RTTICollectionUtils');
_lazyRequire('convertJSNumberArrayToNativeUInt32Vector', 'RTTICollectionUtils');
_lazyRequire('convertVec2VectorToJSArray', 'RTTICollectionUtils');
_lazyRequire('convertJSArrayToVec2Vector', 'RTTICollectionUtils');
_lazyRequire('convertVec3VectorToJSArray', 'RTTICollectionUtils');
_lazyRequire('convertJSArrayToVec3Vector', 'RTTICollectionUtils');
_lazyRequire('convertVec4VectorToJSArray', 'RTTICollectionUtils');
_lazyRequire('convertJSArrayToVec4Vector', 'RTTICollectionUtils');
_lazyRequire('convertQuatVectorToJSArray', 'RTTICollectionUtils');
_lazyRequire('convertJSArrayToQuatVector', 'RTTICollectionUtils');
_lazyRequire('AlgorithmManager', 'AlgorithmManager');
_lazyRequire('AlgorithmInputConfig', 'AlgorithmManager');
_lazyRequire('AlgorithmGraphNode', 'AlgorithmManager');
_lazyRequire('FaceAction', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('FaceAttrExpression', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('FaceAttrGender', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('FaceGanObjectType', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('FacePetType', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('HandAction', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('SnapShotRet', 'AlgorithmEnumsAndInterfaces');
_lazyRequire('TimelinePlayer', 'TimelinePlayer');
_lazyRequire('Timeline', 'TimelineCore');
_lazyRequire('TimelineAsset', 'TimelineCore');
_lazyRequire('TimelineClip', 'TimelineClip');
_lazyRequire('TimelineTrack', 'TimelineTrack');
_lazyRequire('TimelineActivityTrack', 'TimelineActivityTrack');
_lazyRequire('TimelineActivityTrackAsset', 'TimelineActivityTrack');
_lazyRequire('TimelineActivityClip', 'TimelineActivityClip');
_lazyRequire('TimelineActivityClipAsset', 'TimelineActivityClip');
_lazyRequire('TimelineKeyFrameTrack', 'TimelineKeyFrameTrack');
_lazyRequire('TimelineKeyFrameTrackAsset', 'TimelineKeyFrameTrack');
_lazyRequire('TimelineKeyFrameClip', 'TimelineKeyFrameClip');
_lazyRequire('TimelineKeyFrameClipAsset', 'TimelineKeyFrameClip');
_lazyRequire('TimelineSignalTrackAsset', 'TimelineSignalTrack');
_lazyRequire('TimelineSignalTrack', 'TimelineSignalTrack');
_lazyRequire('TimelineSignalClipAsset', 'TimelineSignalClip');
_lazyRequire('TimelineSignalClip', 'TimelineSignalClip');
_lazyRequire('TimelineAnimationTrack', 'TimelineAnimationTrack');
_lazyRequire('TimelineAnimationTrackAsset', 'TimelineAnimationTrack');
_lazyRequire('TimelineAnimationClip', 'TimelineAnimationClip');
_lazyRequire('TimelineAnimationClipAsset', 'TimelineAnimationClip');
_lazyRequire('TimelineSubTrack', 'TimelineSubTrack');
_lazyRequire('TimelineSubTrackAsset', 'TimelineSubTrack');
_lazyRequire('TimelineSubClip', 'TimelineSubClip');
_lazyRequire('TimelineSubClipAsset', 'TimelineSubClip');
_lazyRequire('TimelineComposeTrack', 'TimelineComposeTrack');
_lazyRequire('TimelineComposeTrackAsset', 'TimelineComposeTrack');
_lazyRequire('TimelineComposeClip', 'TimelineComposeClip');
_lazyRequire('TimelineComposeClipAsset', 'TimelineComposeClip');
_lazyRequire('TimelineMediaTrackAsset', 'TimelineMediaTrack');
_lazyRequire('TimelineMediaTrack', 'TimelineMediaTrack');
_lazyRequire('TimelineMediaClipAsset', 'TimelineMediaClip');
_lazyRequire('TimelineMediaClip', 'TimelineMediaClip');
_lazyRequire('TimelineTextTemplateTrackAsset', 'TimelineTextTemplateTrack');
_lazyRequire('TimelineTextTemplateTrack', 'TimelineTextTemplateTrack');
_lazyRequire('TimelineTextTemplateClipAsset', 'TimelineTextTemplateClip');
_lazyRequire('TimelineTextTemplateClip', 'TimelineTextTemplateClip');
_lazyRequire('TimelineText2DTrackAsset', 'TimelineText2DTrack');
_lazyRequire('TimelineText2DTrack', 'TimelineText2DTrack');
_lazyRequire('TimelineText2DClipAsset', 'TimelineText2DClip');
_lazyRequire('TimelineText2DClip', 'TimelineText2DClip');
_lazyRequire('TimelineTextureTrackAsset', 'TimelineTextureTrack');
_lazyRequire('TimelineTextureTrack', 'TimelineTextureTrack');
_lazyRequire('TimelineTextureClipAsset', 'TimelineTextureClip');
_lazyRequire('TimelineTextureClip', 'TimelineTextureClip');
_lazyRequire('TimelineSubKeyFrameTrackAsset', 'TimelineSubKeyFrameTrack');
_lazyRequire('TimelineSubKeyFrameTrack', 'TimelineSubKeyFrameTrack');
_lazyRequire('TimelineAudioTrackAsset', 'TimelineAudioTrack');
_lazyRequire('TimelineAudioTrack', 'TimelineAudioTrack');
_lazyRequire('TimelineAudioClipAsset', 'TimelineAudioClip');
_lazyRequire('TimelineAudioClip', 'TimelineAudioClip');
_lazyRequire('TimelineAssetUtils', 'TimelineCore');
_lazyRequire('TimelineDurationMode', 'TimelineCore');
_lazyRequire('TimelineTrackAsset', 'TimelineTrack');
_lazyRequire('TimelineClipAsset', 'TimelineClip');
_lazyRequire('TimelineExtrapolation', 'TimelineClip');
_lazyRequire('TimelinePlayMode', 'TimelinePlayer');
_lazyRequire('TimelineInitialValue', 'TimelineCore');
_lazyRequire('TimelineInitialValues', 'TimelineCore');
_lazyRequire('TimelineBaseObject', 'TimelineCommon');
_lazyRequire('SceneBindings', 'TimelineCore');
_lazyRequire('TimelineTrackDataType', 'TimelineAnimationUtils');
_lazyRequire('TimelineSubTrackType', 'TimelineCore');
_lazyRequire('TimelineKFTrackObjectType', 'TimelineAnimationUtils');
_lazyRequire('TimeLineAnimationUtils', 'TimelineAnimationUtils');
_lazyRequire('EasingType', 'TimelineAnimationUtils');
_lazyRequire('TimelineEasingValue', 'TimelineAnimationUtils');
_lazyRequire('KeyFrameTrackAsset', 'TimelineAnimationUtils');
_lazyRequire('KeyFrameAsset', 'TimelineAnimationUtils');
_lazyRequire('AeSlot', 'AfterEffectCommon');
_lazyRequire('AeBundle', 'AfterEffectCommon');
_lazyRequire('AeBundleRenderer', 'AfterEffectCommon');
_lazyRequire('AESlotType', 'AfterEffectCommon');
_lazyRequire('AeSlotText', 'AfterEffectCommon');
_lazyRequire('AeSlotImage', 'AfterEffectCommon');
_lazyRequire('VFXSlot', 'VFXCommon');
_lazyRequire('VFXSlotBool', 'VFXCommon');
_lazyRequire('VFXSlotFloat', 'VFXCommon');
_lazyRequire('VFXSlotInt', 'VFXCommon');
_lazyRequire('VFXSlotTexture', 'VFXCommon');
_lazyRequire('VFXSlotVector2f', 'VFXCommon');
_lazyRequire('VFXSlotVector3f', 'VFXCommon');
_lazyRequire('VFXSlotVector4f', 'VFXCommon');
_lazyRequire('VFXSlotType');
_lazyRequire('VFXSlotColor', 'VFXCommon');
globalDefine.globalRTTINameToAPJSName.set("Entity", "SceneObject");
globalDefine.globalRTTINameToAPJSName.set("Mesh", "Mesh");
globalDefine.globalRTTINameToAPJSName.set("Face3DMesh", "Mesh");
globalDefine.globalRTTINameToAPJSName.set("DepthStencilState", "StencilState");
globalDefine.globalRTTINameToAPJSName.set("ColorBlendState", "BlendState");
globalDefine.globalRTTINameToAPJSName.set("Image", "ImageAsset");
globalDefine.globalRTTINameToAPJSName.set("Texture", "Texture");
globalDefine.globalRTTINameToAPJSName.set("Texture2D", "Texture");
globalDefine.globalRTTINameToAPJSName.set("TextureCube", "Texture");
globalDefine.globalRTTINameToAPJSName.set("Texture3D", "Texture");
globalDefine.globalRTTINameToAPJSName.set("RenderTexture", "Texture");
globalDefine.globalRTTINameToAPJSName.set("ScreenRenderTexture", "Texture");
globalDefine.globalRTTINameToAPJSName.set("SceneOutputRT", "Texture");
globalDefine.globalRTTINameToAPJSName.set("TextureDelegate", "Texture");
globalDefine.globalRTTINameToAPJSName.set("DrawTexture", "Texture");
globalDefine.globalRTTINameToAPJSName.set("TouchPointer", "TouchData");
globalDefine.globalRTTINameToAPJSName.set("VFXProfile", "VisualEffectAsset");
globalDefine.globalRTTINameToAPJSName.set("VFXEffectBlock", "VisualEffect");
globalDefine.globalRTTINameToAPJSName.set("Animaz", "Animation");
globalDefine.globalRTTINameToAPJSName.set("ImageRenderer", "Image");
globalDefine.globalRTTINameToAPJSName.set("AudioClip", "AudioAsset");
globalDefine.globalRTTINameToAPJSName.set("AnimazTrack", "AnimationTrack");
globalDefine.globalRTTINameToAPJSName.set("EffectFaceMakeup", "FaceMakeup");
globalDefine.globalRTTINameToAPJSName.set("EffectFaceMakeupFaceU", "FaceMakeup");
globalDefine.globalRTTINameToAPJSName.set("EffectFacePupilV2", "FaceMakeupIris");
globalDefine.globalRTTINameToAPJSName.set("Envmap", "EnvironmentLight");
globalDefine.globalRTTINameToAPJSName.set("AMGPhysicsMaterial", "PhysicsMaterial");
globalDefine.globalRTTINameToAPJSName.set("PngMeta", "TextureMeta");
globalDefine.globalRTTINameToAPJSName.set("AnimazClip", "AnimationClip");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioGraph", "AudioGraph");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioNodePin", "AudioNodePin");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioNodePout", "AudioNodePout");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioNode", "AudioGraphNode");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioSourceNode", "AudioSourceNode");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioMicSourceNode", "AudioMicSourceNode");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioMusicSourceNode", "AudioMusicSourceNode");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioGainNode", "AudioGainNode");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioEffectNode", "AudioEffectNode");
globalDefine.globalRTTINameToAPJSName.set("AMGAudioExtractorNode", "AudioExtractorNode");
globalDefine.globalRTTINameToAPJSName.set("AnimLayer", "AnimationLayer");
globalDefine.globalRTTINameToAPJSName.set("AnimStateTransition", "AnimationStateTransition");
globalDefine.globalRTTINameToAPJSName.set("AnimState", "AnimationState");
try {
        const pluginComponentsPath = './Plugins/index.js';
        const {pluginComponents} = require(pluginComponentsPath);
        pluginComponents.forEach((value, key) => {
            const relativePath = '../Plugins/' + value;
            _lazyRequire(key, relativePath);
        });
    } catch (e) {
    }
try {
        const customComponentsPath = './UserComponentsIndex.js';
        const {customComponents} = require(customComponentsPath);
        customComponents.forEach((value, key) => {
            if (value.endsWith('.js')) {
                const relativePath = '../' + value;
                _lazyRequire(key, relativePath);
            }
        });
    } catch (e) {
    }
